# Generated by Django 3.2.8 on 2021-10-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用戶名')),
                ('password', models.CharField(max_length=64, verbose_name='用戶密碼')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='用戶token')),
            ],
        ),
    ]
