# Generated by Django 3.0.5 on 2021-10-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20211025_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='candidate',
            field=models.IntegerField(null=True),
        ),
    ]
