# Generated by Django 3.0.5 on 2021-10-27 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20211026_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_photo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ig_photo',
        ),
        migrations.DeleteModel(
            name='CandidateDetail',
        ),
        migrations.AddField(
            model_name='igphoto',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.UserInfo'),
        ),
    ]
