# Generated by Django 3.0.5 on 2021-10-27 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20211027_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igphoto',
            name='ig_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='igphoto',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.UserInfo'),
        ),
    ]
