# Generated by Django 3.0.5 on 2021-10-27 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20211027_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='igphoto',
            name='userinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.UserInfo'),
        ),
        migrations.AlterField(
            model_name='igphoto',
            name='username',
            field=models.CharField(max_length=32, null=True, verbose_name='用戶名'),
        ),
    ]
