# Generated by Django 3.0.5 on 2021-10-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_igphoto_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
